CREATE TABLE [dbo].[Vaishnav] (
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [FirstName]            NVARCHAR (100)  NOT NULL,
    [MiddleName]           NVARCHAR (100)  NULL,
    [LastName]             NVARCHAR (100)  NULL,
    [Nickname]             NVARCHAR (100)  NULL,
    [Address]              NVARCHAR (1000) NULL,
    [CountryId]            INT             NULL,
    [StateId]              INT             NULL,
    [CityId]               INT             NULL,
    [VillageId]            INT             NULL,
    [Area]                 NVARCHAR (100)  NULL,
    [PostalCode]           NVARCHAR (50)   NULL,
    [Gender]               VARCHAR (20)    NULL,
    [MaritalStatus]        VARCHAR (20)    NULL,
    [DateOfBirth]          DATETIME        NULL,
    [BloodGroup]           VARCHAR (10)    NULL,
    [MobileNo]             VARCHAR (15)    NULL,
    [Email]                VARCHAR (50)    NULL,
    [ResidencePhone]       VARCHAR (20)    NULL,
    [Occupation]           INT             NULL,
    [OccupationDetail]     NVARCHAR (1000) NULL,
    [OccupationAddress]    NVARCHAR (1000) NULL,
    [OccupationCountryId]  INT             NULL,
    [OccupationStateId]    INT             NULL,
    [OccupationCityId]     INT             NULL,
    [OccupationVillageId]  INT             NULL,
    [OccupationArea]       NVARCHAR (1000) NULL,
    [OccupationPostalCode] NVARCHAR (100)  NULL,
    [OfficePhone]          VARCHAR (25)    NULL,
    [AddtionalNote]        NVARCHAR (1000) NULL,
    [IsActive]             BIT             CONSTRAINT [DF_Vaishnav_IsActive] DEFAULT ((1)) NULL,
    [CreatedOn]            DATETIME        CONSTRAINT [DF_Vaishnav_CreatedOn] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]            INT             NOT NULL,
    [UpdatedOn]            DATETIME        NULL,
    [UpdatedBy]            INT             NULL,
    [DeletedOn]            DATETIME        NULL,
    [DeletedBy]            INT             NULL,
    [IsDeleted]            BIT             CONSTRAINT [DF_Vaishnav_IsDeleted] DEFAULT ((0)) NOT NULL,
    [VaishnavId]           VARCHAR (25)    NULL,
    CONSTRAINT [PK_Vaishnav] PRIMARY KEY CLUSTERED ([Id] ASC)
);

