/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
if not exists(select * from dbo.AccountGroup)
Begin
SET IDENTITY_INSERT dbo.AccountGroup ON 
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (1, N'Capital Account', N'', 1, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (2, N'Advances Assets', N'Advances Assets', 2, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (3, N'Bank Accounts', N'', 2, 1, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (4, N'Cash-in hand', N'', 2, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (5, N'Current Assets', N'', 2, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (6, N'Deposits (Asset)', N'', 2, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (7, N'Integrated Accounts-cum-Inventory', N'', 2, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (8, N'Loans & Advances (Asset)', N'', 2, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (9, N'Non-integrated Accounts-cum-Inventory', N'', 2, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (10, N'Stock-in-hand', N'', 2, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (11, N'Sundry Debtors', N'', 2, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (12, N'ADVANCE FOR PROPERTY', N'ADVANCE FOR PROPERTY', 3, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (13, N'Current Liabilities', N'', 3, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (14, N'Duties and Taxes', N'', 3, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (15, N'FINANCE EXPENSES', N'FINANCE EXPENSES', 3, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (16, N'Provisions', N'', 3, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (17, N'Sundry Creditors', N'', 3, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, 5, N'Annexure 4 Sundry Creditors for Expenses', 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (18, N'Investments', N'', 4, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, 8, N'Annexure 3 A', 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (19, N'Bank OCC A/c', N'', 5, 1, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (20, N'Bank OD Accounts', N'', 5, 1, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (21, N'Loans (Liability)', N'', 5, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (22, N'Secured Loans', N'', 5, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (23, N'Unsecured Loans', N'', 5, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (24, N'Loans and Advances (Asset) group', N'', 6, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (25, N'Suspense Account', N'', 6, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (26, N'Miscellaneous Expenses (Asset)', N'', 7, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (27, N'Branch/Divisions', N'', 8, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (28, N'Sales Account', N'', 9, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (29, N'Purchase Account', N'', 10, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (30, N'Bhet Income', N'Bhet Income', 11, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (31, N'Direct Income Income Direct', N'', 11, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (32, N'Donation', N'Donation', 11, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (33, N'Miscellaneous Income', N'Miscellaneous Income', 11, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (34, N'Indirect Income Income Indirect', N'', 12, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (35, N'Direct Expenses Expenses Direct', N'', 13, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (36, N'EXPENSES FOR THE OBJECT OF TRUST', N'EXPENSES FOR THE OBJECT OF TRUST', 13, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, 10, N'Annexure 9 EXPENSES FOR THE OBJECT OF TRUST', 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (37, N'OFFICE & ADMINISTRATION', N'OFFICE & ADMINISTRATION', 13, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, 9, N'Annexure 8 Office & Administration', 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (38, N'REPAIRS & MAINTENANCE', N'REPAIRS & MAINTENANCE', 13, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (39, N'Indirect Expenses Expenses Indirect', N'', 14, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (40, N'Immovable property', N'Immovable property', 15, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, 1, N'Annexure 1', 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (41, N'Movable Property', N'Movable Property', 15, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, 2, N'Annexure 1', 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (42, N'Funds', N'Funds', 16, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
INSERT dbo.AccountGroup (Id, GroupName, AliasName, DefaultGroupId, GroupType, IsActive, IsEditable, CreatedBy, CreatedOn, UpdatedBy, UpdatedOn, DeletedBy, DeletedOn, IsDelete, AnnexureOrder, AnnexureName, IsDefaultRecord) 
VALUES (43, N'Profit C/F', N'Profit C/F', 17, 0, 1, 0, 2, GETDATE(), NULL, NULL, NULL, NULL, 0, NULL, NULL, 1)
SET IDENTITY_INSERT dbo.AccountGroup OFF
end