/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM $(TableName)					
--------------------------------------------------------------------------------------
*/
if not exists(select * from dbo.Manorath)
Begin
SET IDENTITY_INSERT dbo.Manorath ON 

INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (1, N'Samgri - Salabadi - Kayami Manorath', CAST(0.00 AS Decimal(18, 2)), 4, 1, 3, 4, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (2, N'Dan Bhet', CAST(0.00 AS Decimal(18, 2)), 1, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (3, N'Mangalbhog - Salabadi - Kayami', CAST(0.00 AS Decimal(18, 2)), 4, 1, 3, 4, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (4, N'Rajbhog Danbhet', CAST(1100.00 AS Decimal(18, 2)), 3, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (5, N'Rajbhog Kayami', CAST(0.00 AS Decimal(18, 2)), 4, 1, 3, 4, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (6, N'Palna Kayami', CAST(0.00 AS Decimal(18, 2)), 4, 1, 3, 4, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (7, N'Uthapan Kayami', CAST(0.00 AS Decimal(18, 2)), 4, 1, 3, 4, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (8, N'Gopashtmi Kayami', CAST(0.00 AS Decimal(18, 2)), 4, 1, 3, 4, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (9, N'Nek Ni Seva - Akho Divas', CAST(0.00 AS Decimal(18, 2)), 4, 1, 3, 4, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (10, N'Gaushala Seva', CAST(0.00 AS Decimal(18, 2)), 1, 1, 3, 19, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (11, N'Akha Divas No', CAST(2501.00 AS Decimal(18, 2)), 3, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (12, N'Palna', CAST(501.00 AS Decimal(18, 2)), 3, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (13, N'Mangal Bhog', CAST(351.00 AS Decimal(18, 2)), 3, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (14, N'Shayan bhog', CAST(501.00 AS Decimal(18, 2)), 3, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (15, N'Ful Mandali', CAST(1501.00 AS Decimal(18, 2)), 3, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (16, N'Nav Manorath', CAST(2501.00 AS Decimal(18, 2)), 3, 1, 3, 23, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (17, N'Adhik Maas', CAST(0.00 AS Decimal(18, 2)), 1, 1, 3, 22, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (18, N'Hindora', CAST(0.00 AS Decimal(18, 2)), 1, 1, 3, 21, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (19, N'Rathyatra', CAST(0.00 AS Decimal(18, 2)), 1, 1, 3, 23, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (20, N'Gopashtmi', CAST(2501.00 AS Decimal(18, 2)), 3, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (21, N'Vrajkamal', CAST(500.00 AS Decimal(18, 2)), 3, 1, 3, 23, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (22, N'Ankut Samagri', CAST(500.00 AS Decimal(18, 2)), 3, 1, 3, 23, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (23, N'Dipdan', CAST(500.00 AS Decimal(18, 2)), 3, 1, 3, 23, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (24, N'Shidhdhkal Samagri', CAST(150.00 AS Decimal(18, 2)), 1, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (25, N'Gangore', CAST(2501.00 AS Decimal(18, 2)), 3, 1, 3, 23, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (26, N'ChhakManorath', CAST(11001.00 AS Decimal(18, 2)), 3, 1, 3, 23, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (27, N'Nand Mohtsav', CAST(5000.00 AS Decimal(18, 2)), 3, 1, 3, 23, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (28, N'Bungalow', CAST(1100.00 AS Decimal(18, 2)), 3, 1, 3, 23, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (29, N'Vivah Khel', CAST(500.00 AS Decimal(18, 2)), 3, 1, 3, 23, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (30, N'Sanmukh Bhet', CAST(0.00 AS Decimal(18, 2)), 1, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (31, N'Golakh Bhet', CAST(0.00 AS Decimal(18, 2)), 1, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (32, N'Dipakji Golakh', CAST(0.00 AS Decimal(18, 2)), 1, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (33, N'Shaksamagri bhet', CAST(0.00 AS Decimal(18, 2)), 1, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (34, N'Prabodhini Ekadasi', CAST(500.00 AS Decimal(18, 2)), 3, 1, 3, 2, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
INSERT dbo.Manorath (Id, ManorathName, Nyochhawar, ManorathType, CashAccountId, ChequeAccountId, VaishnavAccountId, DarshanId, IsActive, IsDeleted, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy, DeletedOn, DeletedBy, IsDefaultRecord) 
VALUES (35, N'Ghee Bhet', CAST(0.00 AS Decimal(18, 2)), 1, 1, 3, 26, NULL, 1, 0, GETDATE(), 2, NULL, NULL, NULL, NULL, 1)
SET IDENTITY_INSERT dbo.Manorath OFF
end