/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM $(TableName)					
--------------------------------------------------------------------------------------
*/
if not exists(select * from dbo.Occupation)
Begin
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (1, N'3D animator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (2, N'Abattoir worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (3, N'Aboriginal and Torres Strait Islander health worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (4, N'Accessory designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (5, N'Accountant (general)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (6, N'Accounts clerk', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (7, N'Actor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (10, N'Actuary', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (11, N'Acupuncturist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (12, N'Advertising designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (13, N'Advertising specialist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (14, N'Aeronautical engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (15, N'Aeroplane pilot', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (16, N'Aged care worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (17, N'Agricultural consultant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (18, N'Agricultural engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (19, N'Agricultural scientist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (20, N'Air combat officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (21, N'Air force - general entrant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (22, N'Air force technician/tradesperson', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (23, N'Air traffic controller', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (24, N'Air-conditioning and refrigeration mechanic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (25, N'Aircraft baggage handler and airline ground crew', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (26, N'Aircraft maintenance engineer (avionics)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (27, N'Aircraft maintenance engineer (mechanical)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (28, N'Aircraft maintenance engineer (structural)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (29, N'Alarm, security or surveillance monitor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (30, N'Ambulance officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (31, N'Anaesthetist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (32, N'Anchorman', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (33, N'Anesthesiologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (34, N'Anesthesiologist Assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (35, N'Anesthesiology Fellow', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (36, N'Animal attendants and trainers', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (37, N'Animator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (39, N'Aquaculture farmer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (40, N'Arborist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (41, N'Archaeologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (42, N'Architect', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (43, N'Architectural draftsperson', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (44, N'Archivist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (45, N'Army officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (46, N'Army Soldier - Technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (47, N'Art administrator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (48, N'Art director (film, television, stage)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (49, N'Art teacher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (50, N'Artisan', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (51, N'Artistic director', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (52, N'Arts administration', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (53, N'Assistant Podiatrist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (54, N'Athletic Trainer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (55, N'Auctioneer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (56, N'Audiologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (58, N'Audiovisual technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (59, N'Auditor (external and internal)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (60, N'Author', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (62, N'Auto mechanic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (63, N'Automotive electrician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (64, N'Backup dancer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (65, N'Baker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (67, N'Ballet dancer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (68, N'Bank worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (69, N'Bar attendant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (70, N'Bariatric Surgeon', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (71, N'Barista', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (72, N'Barrister', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (73, N'Bartender', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (74, N'Beader', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (75, N'Beauty therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (76, N'Beef cattle farmer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (77, N'Bicycle mechanic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (78, N'Binder and finisher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (79, N'Biokineticist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (80, N'Biomedical engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (81, N'Biosecurity officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (82, N'Biotechnologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (83, N'Blogger', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (84, N'Boat builder and repairer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (85, N'Bobbin boy', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (86, N'Body artist or tattooist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (87, N'Boiler or engine operator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (88, N'Book coach', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (89, N'Book or script editor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (90, N'Bookkeeper', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (91, N'Bookmaker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (92, N'Botanist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (93, N'Brewer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (94, N'Bricklayer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (95, N'Broadcast transmitter operator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (96, N'Builder''s Labourer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (97, N'Building insulation installer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (98, N'Building surveyor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (99, N'Bus driver', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (100, N'Business machine mechanic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (101, N'Butcher or smallgoods maker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (102, N'Cabinetmaker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (103, N'Cafe or restaurant manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (104, N'Call or contact centre operator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (105, N'Call or contact centre team leader', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (106, N'Caller (dancing)', 1)

INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (107, N'Camera operator (film, television or video)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (108, N'Canvas goods fabricator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (109, N'Car park attendant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (110, N'Cardiac Surgeon', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (111, N'Cardiologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (113, N'Cardiology Fellow', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (114, N'Cardiothoracic surgeon', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (116, N'Careers counsellor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (117, N'Carpenter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (118, N'Cartographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (119, N'Cartoonist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (120, N'Cashier', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (121, N'Casting director', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (122, N'Ceramics artist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (123, N'Certified Emergency Registered Nurse', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (124, N'Certified Emergency Registered Respiratory Therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (125, N'Certified Registered Nurse Anesthetist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (126, N'Certified Respiratory Therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (127, N'Chef', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (128, N'Chemical engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (129, N'Chemist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (130, N'Chief administrative officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (131, N'Chief analytics officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (132, N'Chief brand officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (133, N'Chief business development officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (134, N'Chief business officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (135, N'Chief commercial officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (136, N'Chief communications officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (137, N'Chief compliance officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (138, N'Chief content officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (139, N'Chief creative officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (141, N'Chief customer officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (142, N'Chief data officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (143, N'Chief design officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (144, N'Chief digital officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (145, N'Chief diversity officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (146, N'Chief events officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (147, N'Chief executive officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (148, N'Chief executive or managing director', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (149, N'Chief experience officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (150, N'Chief financial officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (151, N'Chief gaming officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (152, N'Chief genealogical officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (153, N'Chief human resources officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (154, N'Chief information officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (155, N'Chief information officer (higher education)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (156, N'Chief information security officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (157, N'Chief innovation officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (158, N'Chief investment officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (159, N'Chief knowledge officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (160, N'Chief learning officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (161, N'Chief legal officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (162, N'Chief marketing officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (163, N'Chief operating officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (164, N'Chief privacy officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (165, N'Chief process officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (166, N'Chief product officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (167, N'Chief reputation officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (168, N'Chief research officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (169, N'Chief restructuring officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (170, N'Chief revenue officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (171, N'Chief risk officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (172, N'Chief scientific officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (173, N'Chief security officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (174, N'Chief services officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (175, N'Chief strategy officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (176, N'Chief sustainability officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (177, N'Chief technology officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (178, N'Chief visibility officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (179, N'Chief visionary officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (180, N'Chief web officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (181, N'Child care centre manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (182, N'Child protection worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (183, N'Chiropractor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (185, N'Choreographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (187, N'Cinema or theatre manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (188, N'Cinematographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (189, N'Civil celebrant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (190, N'Civil engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (191, N'Civil engineering draftsperson', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (192, N'Civil engineering technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (193, N'Clay, concrete, glass or stone machine operator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (194, N'Clerk of the Chapel', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (195, N'Clinical haematologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (196, N'Clinical psychologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (197, N'Clothing production worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (198, N'Coastal engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (199, N'Colorist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (200, N'Commercial cleaner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (201, N'Commercial housekeeper (hotel/motel room attendant)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (202, N'Commissioning editor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (203, N'Commodities trader', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (204, N'Communications operator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (205, N'Community corrections officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (206, N'Community worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (207, N'Company manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (208, N'Computer engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (209, N'Computer-aided design (CAD) technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (210, N'Concept Artist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (211, N'Concierge', 1)

INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (212, N'Concreter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (213, N'Conductor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (214, N'Confectionery maker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (215, N'Conference and event organiser', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (216, N'Conservation Officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (217, N'Conservator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (218, N'Construction estimator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (219, N'Construction project manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (220, N'Construction rigger', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (221, N'Construction worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (222, N'Contract Administrator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (223, N'Cook', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (224, N'Copy editor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (225, N'Copywriter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (226, N'Corporate general manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (227, N'Costume designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (229, N'Costume Director', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (230, N'Counsellor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (231, N'Court bailiff or sheriff (Aus)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (232, N'Coxswain', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (233, N'Crane chaser (dogger)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (234, N'Crane, hoist or lift operator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (235, N'Creative consultant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (236, N'Crew Chief', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (237, N'Critical Care Nurse Practitioner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (238, N'Critical Care Registered Nurse', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (239, N'Critical Care Respiratory Therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (240, N'CT Radiographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (241, N'Curator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (242, N'Customer service manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (243, N'Customs officer (Border Force officer)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (244, N'Dairy cattle farmer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (245, N'dance journalist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (246, N'Dance therapy', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (247, N'Dancer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (249, N'Dancer or choreographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (250, N'Debt collector', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (251, N'Deck hand', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (252, N'Delivery driver', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (253, N'Dental assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (254, N'Dental hygienist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (255, N'Dental specialist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (256, N'Dental technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (257, N'Dental therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (258, N'Dentist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (259, N'Dermatologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (261, N'Design director', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (262, N'Design strategist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (263, N'Developer programmer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (264, N'Dialysis Technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (265, N'Diesel motor mechanic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (266, N'Dietitian', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (267, N'Director', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (268, N'Director (film, television, radio or stage)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (269, N'Director of Audience Services', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (270, N'Director of development', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (271, N'Director of Production', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (272, N'Director of Public Relations', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (273, N'Director of Special Events', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (274, N'Disability services officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (275, N'Disability worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (276, N'Diver', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (277, N'Diversional therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (278, N'Doctor of Podiatric Medicine', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (279, N'Dog handler or trainer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (280, N'Dog writer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (281, N'Domestic cleaner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (282, N'Doorperson or luggage porter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (283, N'Dramaturg', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (284, N'Dresser', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (285, N'Driller', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (286, N'Drilling engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (287, N'Driving instructor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (288, N'Drug and alcohol counsellor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (289, N'Drycleaner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (290, N'Early childhood (pre-primary school) teacher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (291, N'Early childhood educator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (292, N'Earth science technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (293, N'Earthmoving plant operator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (294, N'Economist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (295, N'Electorate officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (296, N'Electrical engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (297, N'Electrical engineering draftsperson', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (298, N'Electrical engineering technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (299, N'Electrical linesworker (Aus)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (300, N'Electrician (general)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (301, N'Electronic engineering technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (302, N'Electronic equipment trades worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (303, N'Electronic instrument trades worker (general)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (304, N'Electronics engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (305, N'Electroplater', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (306, N'Embalmer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (307, N'Emergency Medical Technician - Basic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (308, N'Emergency Medical Technician - Critical Care Paramedic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (309, N'Emergency Medical Technician - Intermediate 85', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (310, N'Emergency Medical Technician - Intermediate 99', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (311, N'Emergency Medical Technician - Paramedic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (312, N'Emergency medicine specialist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (313, N'Emergency Nurse Practitioner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (314, N'Emergency physician', 1)

INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (315, N'Emergency Physician Assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (316, N'Endocrinologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (318, N'Engineering patternmaker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (319, N'Engraver', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (320, N'Enrolled nurse', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (321, N'Entertainer or variety artist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (322, N'Entrepreneur', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (323, N'Environmental consultant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (324, N'Environmental engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (325, N'Environmental health officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (326, N'Environmental manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (327, N'Environmental research scientist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (328, N'Essayist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (329, N'Event planner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (330, N'Executive producer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (331, N'Exercise scientist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (332, N'Exotic dancer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (333, N'Facilities manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (334, N'Factory worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (335, N'Family Nurse Practitioner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (336, N'Family Practice Physician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (337, N'Farm manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (338, N'Fashion designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (340, N'Fast food cook', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (341, N'Filling station attendant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (342, N'Film and video producer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (343, N'Film director', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (344, N'Film producer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (345, N'Finance broker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (346, N'Financial institution branch manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (347, N'Financial investment adviser', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (348, N'Financial investment manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (349, N'Fine artist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (350, N'Fire fighter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (351, N'Fisheries officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (352, N'Fishing hand', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (353, N'Fitness instructor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (354, N'Flight attendant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (355, N'Flight Nurse', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (356, N'Floor finisher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (357, N'Floral designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (358, N'Florist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (359, N'Flying instructor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (360, N'Food processing worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (361, N'Food technologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (362, N'Foreman', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (363, N'Forensic scientist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (364, N'Forester (Aus)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (365, N'Forklift driver', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (366, N'Freelancer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (367, N'Fruit and vegetable picker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (368, N'Funeral director', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (369, N'Furniture finisher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (370, N'Furniture removalist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (371, N'Gallery or museum curator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (372, N'Gallery or museum guide', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (373, N'Gallery or museum technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (374, N'Game developer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (375, N'Gaming worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (376, N'Gardener (general)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (377, N'Gasfitter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (378, N'Gastroenterologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (380, N'General clerk', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (381, N'General Doctor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (382, N'General medical practitioner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (383, N'General practitioner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (384, N'Geologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (385, N'Geophysicist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (386, N'Geotechnical engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (387, N'Geriatrician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (388, N'Gerontological Nurse Practitioner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (389, N'Ghostwriter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (390, N'Glazier', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (391, N'Goldsmith', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (392, N'Grain oilseed or pasture grower', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (393, N'Grape grower', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (394, N'Graphic designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (396, N'Graphic pre-press trades worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (397, N'Greenkeeper', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (398, N'Griot', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (399, N'Grips', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (400, N'Gunsmith', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (401, N'Gynaecologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (403, N'Hack writer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (404, N'Haematologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (405, N'Hairdresser', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (406, N'Hairstylist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (407, N'Handyperson', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (408, N'Health information manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (409, N'Health promotion officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (410, N'Healthcare Chaplain', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (411, N'Helicopter pilot', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (412, N'Hepatic Biliary Pancreatic Surgeon', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (413, N'Historian', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (414, N'Horse trainer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (415, N'Hospital pharmacist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (416, N'Hotel or motel manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (417, N'House manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (418, N'Human resource adviser', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (419, N'Human resource manager', 1)

INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (420, N'Hydrologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (421, N'ICT business analyst', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (422, N'ICT project manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (423, N'ICT security specialist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (424, N'ICT support technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (425, N'ICT systems test engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (426, N'Illustrator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (427, N'Immigration officer (Border Force officer)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (428, N'Industrial designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (429, N'Industrial engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (430, N'Industrial pharmacist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (431, N'Infopreneur', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (432, N'Information technology administrator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (433, N'Insurance agent', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (434, N'Insurance broker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (435, N'Intelligence officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (436, N'Intensive care specialist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (437, N'Intensivist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (438, N'Interior designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (440, N'Internist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (441, N'Interpreter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (442, N'Interventional Radiographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (443, N'Jackeroo/Jillaroo', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (444, N'Janitor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (445, N'Jewellery designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (447, N'Jockey', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (448, N'Joiner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (449, N'Journalist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (451, N'Judge', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (452, N'Kitchenhand', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (453, N'Laboratory manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (454, N'Laboratory technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (455, N'Lactation consultant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (456, N'Landscape architect', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (457, N'Landscape gardener', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (458, N'Laundry worker (general)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (459, N'Law clerk', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (460, N'Legal secretary', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (461, N'Librarian', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (462, N'Library assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (463, N'Library technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (464, N'Lifeguard', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (465, N'Light technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (466, N'Lighting designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (467, N'Lighting technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (468, N'Literary editor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (469, N'Literary Manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (470, N'Locksmith', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (471, N'Logistics clerk', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (472, N'Lyricist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (473, N'Machine shorthand reporter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (474, N'Maintenance engineering', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (475, N'Maintenance planner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (476, N'Make up artist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (477, N'Make-up artist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (479, N'Makeup designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (480, N'Mammographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (481, N'Managing director or General manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (482, N'Manuscript format', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (483, N'Marine biologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (484, N'Marine designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (485, N'Marine fabricator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (486, N'Marine surveyor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (487, N'Market research analyst', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (488, N'Marketing Director', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (489, N'Marketing specialist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (490, N'Massage therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (491, N'Master fisher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (492, N'Materials engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (493, N'Materials recycler', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (494, N'Materials technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (495, N'Mathematician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (496, N'Meat inspector', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (497, N'Mechanic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (498, N'Mechanical engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (499, N'Mechanical engineering draftsperson', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (500, N'Mechanical engineering technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (501, N'Mechanical fitter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (502, N'Mechatronic engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (503, N'Media designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (504, N'Medical administrator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (505, N'Medical diagnostic radiographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (506, N'Medical Dosimetry Technologist, also known as a ', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (507, N'Medical laboratory scientist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (508, N'Medical Laboratory Technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (509, N'Medical oncologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (510, N'Medical radiation therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (511, N'Medical writing', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (512, N'Member of parliament', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (513, N'Mental Health Nurse Practitioner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (514, N'Mental health worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (515, N'Metal engineering process worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (516, N'Metal fabricator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (517, N'Metal machinist (first class)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (518, N'Metallurgist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (519, N'Meteorologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (520, N'Meter reader', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (521, N'Microbiologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (522, N'Midwife', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (524, N'Migration agent (Aus)', 1)

INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (525, N'Miller', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (526, N'Milliner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (527, N'Miner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (528, N'Mining engineer (excluding petroleum)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (529, N'Mining production manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (530, N'Mining support worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (531, N'Minister of religion', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (532, N'Mixed crop and livestock farm worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (533, N'Model', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (534, N'Moldmaker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (535, N'Mortgage broker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (536, N'Motion picture projectionist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (537, N'Motor mechanic (general)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (538, N'Motorcycle mechanic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (539, N'Multimedia specialist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (540, N'Music', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (541, N'Music Director', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (542, N'Music teacher (private tuition)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (543, N'Musician (instrumental)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (544, N'Nanny', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (545, N'Naturopath', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (546, N'Naval architect', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (547, N'Navy sailor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (548, N'Navy technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (549, N'Neonatal Nurse Practitioner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (550, N'Neonatalologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (551, N'Neonatologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (552, N'Nephrologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (553, N'Network administrator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (554, N'Network engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (555, N'Neurologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (557, N'Neuroradiographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (558, N'Neurosurgeon', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (560, N'News presenter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (561, N'Newscaster', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (562, N'Novelist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (563, N'Nuclear medicine technologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (564, N'Nurse educator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (565, N'Nurse manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (566, N'Nurse practitioner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (567, N'Nurse-Midwife', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (568, N'Nurseryperson', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (569, N'Nursing clinical director', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (570, N'Nursing support worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (571, N'Nutritionist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (572, N'Obstetrician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (574, N'Occupational health and safety adviser', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (575, N'Occupational therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (577, N'Occupational Therapy Assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (578, N'Office manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (579, N'Offset printer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (580, N'Oncologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (581, N'Ophthalmologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (583, N'Optical mechanic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (584, N'Optometrist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (586, N'Orthopaedic surgeon', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (587, N'Orthopaedic Technologist or Prosthetist & Orthotist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (588, N'Orthopedic Physician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (589, N'Orthoptist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (590, N'Orthotist or prosthetist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (591, N'Osteopath', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (592, N'Otolaryngologist (Ear, Nose and Throat physician)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (593, N'Otorhinolaryngologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (594, N'Outdoor adventure instructor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (595, N'Paediatric surgeon', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (596, N'Paediatrician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (597, N'Painting trades worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (598, N'Panel beater', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (599, N'Panelbeater', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (600, N'Park ranger', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (601, N'Parking inspector', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (602, N'Party planner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (603, N'Pastrycook', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (604, N'Pathologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (605, N'Patient care assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (606, N'Patternmaker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (607, N'Payroll clerk', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (608, N'Pediatric Nurse', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (609, N'Pediatric Nurse Practitioner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (610, N'Pediatric Physician Assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (611, N'Pediatric Respiratory Therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (612, N'Pediatrician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (613, N'Penciller', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (614, N'Personal assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (615, N'Pest controller', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (616, N'Pet groomer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (617, N'Petroleum engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (618, N'Petrophysicist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (619, N'Pharmacist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (621, N'Pharmacologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (622, N'Pharmacy technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (623, N'Phlebotomist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (624, N'Photographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (626, N'Photographer''s assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (627, N'Photojournalist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (628, N'Physical education (PE) teacher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (629, N'Physical Therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (630, N'Physical Therapy Assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (631, N'Physician Assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (632, N'Physicist', 1)

INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (633, N'Physiotherapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (634, N'Picture framer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (635, N'Plant mechanic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (636, N'Plant operator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (637, N'Plastic and reconstructive surgeon', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (638, N'Plastics technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (639, N'Playwright', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (640, N'Plumber', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (641, N'Plumber (general)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (642, N'Podiatric Surgeon', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (644, N'Podiatrist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (646, N'Poet', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (647, N'Police officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (648, N'Policy analyst', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (649, N'Political scientist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (650, N'Polygraph (author)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (651, N'Polymer factory worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (652, N'Postal delivery officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (653, N'Potter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (654, N'Powder coater (spray painter)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (655, N'Power generation plant operator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (656, N'Precision instrument maker and repairer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (657, N'Primary school teacher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (658, N'Printing machinist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (659, N'Prison officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (660, N'Private investigator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (661, N'Process engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (662, N'Process plant operator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (663, N'Producer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (664, N'Product examiner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (665, N'Production designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (666, N'Production manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (668, N'Production manager (manufacturing)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (669, N'Production or plant engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (670, N'Project builder', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (671, N'Project or program administrator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (672, N'Prop and scenery maker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (673, N'Property developer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (674, N'Property manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (675, N'Property master', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (676, N'Psychiatric Nurse Practitioner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (677, N'Psychiatrist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (679, N'Psychologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (681, N'Public relations professional', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (682, N'Publisher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (683, N'Pulmonologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (684, N'Pulmonology Fellow', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (685, N'Quantity Surveyor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (686, N'Radiation oncologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (687, N'Radiation Protection Supervisor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (688, N'Radiation Therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (689, N'Radiation Therapist ', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (690, N'Radio presenter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (691, N'Radio producer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (692, N'Radiographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (693, N'Radiologic Technologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (694, N'Radiologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (696, N'Radiologist Practitioner Assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (697, N'Radiotherapist ', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (698, N'Railway track worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (699, N'Real estate representative', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (700, N'Receptionist (general)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (701, N'Records manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (702, N'Recreation officer (Aus)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (703, N'Recruitment consultant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (704, N'Recycling or rubbish collector', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (705, N'Registered nurse (community health)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (706, N'Registered nurse (mental health)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (707, N'Registered nurse (overview)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (708, N'Registered Respiratory Therapist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (710, N'Renal medicine specialist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (711, N'Répétiteur', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (712, N'Reporter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (713, N'Reporting Radiographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (714, N'Resident medical officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (715, N'Retail buyer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (716, N'Retail manager (general)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (717, N'Retirement village manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (718, N'Review', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (719, N'Rheumatologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (720, N'Road worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (721, N'Roof plumber', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (722, N'Roof tiler', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (723, N'Safety inspector', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (724, N'Sales and marketing manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (725, N'Sales assistant (general)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (726, N'Sales representative', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (727, N'Saw maker and repairer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (728, N'Sawfiler', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (729, N'Sawmill or timber yard worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (730, N'Scaffolder', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (731, N'Scenic designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (732, N'School principal', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (733, N'Screen printer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (734, N'Screenwriter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (737, N'Scribe', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (738, N'Script coordinator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (739, N'Script doctor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (740, N'Scrivener', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (741, N'Sculptor', 1)

INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (742, N'Seafood process worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (743, N'Secondary school teacher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (744, N'Security officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (745, N'Security systems installer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (746, N'Set decorator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (747, N'Set designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (749, N'Set dresser', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (750, N'Settlement agent', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (751, N'Shearer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (752, N'Sheep farmer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (753, N'Sheetmetal trades worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (754, N'Shelf filler', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (755, N'Ship''s engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (756, N'Ship''s master', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (757, N'Ship''s officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (758, N'Shoe repairer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (759, N'Shop foreman', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (760, N'Shotfirer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (761, N'Show control designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (762, N'Showgirl', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (763, N'Signwriter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (764, N'Silversmith', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (765, N'Soaper', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (766, N'Social worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (767, N'Soil scientist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (768, N'Soldier', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (769, N'Solicitor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (770, N'Solid plasterer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (771, N'Songwriter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (772, N'Sonographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (774, N'Sound designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (775, N'Sound technician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (776, N'Special needs teacher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (777, N'Speech Language Pathologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (778, N'Speech pathologist (Aus)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (779, N'Speechwriter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (780, N'Sport Psychologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (781, N'Sports administrator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (782, N'Sports coach or instructor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (783, N'Sports development officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (784, N'Sportsperson', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (785, N'Staff writer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (786, N'Stage Crew', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (787, N'Stage Manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (788, N'Stationary engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (789, N'Statistician', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (790, N'Steel fixer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (791, N'Stockbroking dealer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (792, N'Stonemason', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (793, N'Storeperson', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (794, N'Streetsweeper operator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (795, N'Structural engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (796, N'Stunt coordinator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (797, N'Stunt performer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (798, N'Supply and distribution manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (799, N'Surgeon (general)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (800, N'Surveyor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (801, N'Surveyor''s assistant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (802, N'Systems administrator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (803, N'Systems analyst', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (804, N'Talent agent', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (805, N'Tattoo artist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (806, N'Taxi driver', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (807, N'Teacher of the hearing impaired', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (808, N'Teacher of the sight impaired', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (809, N'Teachers'' aide', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (810, N'Technical cable jointer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (811, N'Technical Director', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (813, N'Technical writer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (814, N'Telecommunications engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (815, N'Textile production worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (816, N'Textile, clothing and footwear mechanic', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (817, N'Therapeutic Radiographer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (818, N'Thoracic medicine specialist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (819, N'Ticket collector or usher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (820, N'Ticketing Agent', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (821, N'Tool pusher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (822, N'Tour guide', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (823, N'Tourist information officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (824, N'Trade union official', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (825, N'Train controller', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (826, N'Train driver', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (827, N'Training and development professional', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (828, N'Transit officer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (829, N'Translator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (830, N'Transport company manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (831, N'Transport engineer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (832, N'Travel consultant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (833, N'Tree faller', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (834, N'Truck driver (general)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (835, N'Turf grower', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (836, N'Tweener', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (837, N'Tyre fitter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (838, N'University lecturer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (839, N'Upholsterer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (840, N'Urban and regional planner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (841, N'Urologist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (843, N'Usher', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (844, N'Valuer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (845, N'Vascular surgeon', 1)

INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (846, N'Vehicle body builder', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (847, N'Veterinarian', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (848, N'Veterinary nurse', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (849, N'Video editor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (851, N'Vineyard worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (852, N'Visual arts and crafts professional', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (853, N'Visual merchandiser', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (854, N'Vocational Education and Training (VET) lecturer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (855, N'Voice actor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (856, N'Waiter', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (858, N'Wall and ceiling fixer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (859, N'Wall and floor tiler', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (860, N'Warehouse administrator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (861, N'Waste water or water plant operator', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (862, N'Watch and clock maker and repairer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (863, N'Water inspector', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (864, N'Waterside worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (865, N'Weatherman/woman', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (866, N'Web designer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (868, N'Website content writer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (869, N'Wedding planner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (870, N'Weight loss consultant', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (871, N'Welder', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (872, N'Welder (first class) (Aus)', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (873, N'Welfare centre manager', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (874, N'Welfare worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (875, N'Wheelwright', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (876, N'Wine maker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (877, N'Women''s Health Nurse Practitioner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (878, N'Wood machinist', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (879, N'Wood turner', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (880, N'Woodworkers', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (881, N'Wool classer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (882, N'Writer', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (884, N'Yoga Instructor', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (885, N'Youth worker', 1)
INSERT dbo.Occupation (Id, Professions, IsDefaultRecord) VALUES (886, N'Zoologist', 1)
End