/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM $(TableName)					
--------------------------------------------------------------------------------------
*/
if not exists(select * from dbo.PageRoleNRights)
Begin
SET IDENTITY_INSERT dbo.PageRoleNRights ON 

INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (1, 1, 1, 1, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (2, 1, 1, 2, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (3, 1, 1, 3, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (4, 1, 1, 4, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (5, 1, 1, 5, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (6, 1, 1, 6, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (7, 1, 1, 7, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (8, 1, 1, 8, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (9, 1, 1, 9, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (10, 1, 1, 10, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (11, 1, 1, 11, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (12, 1, 1, 12, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (13, 1, 1, 13, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (14, 1, 1, 14, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (15, 1, 1, 15, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (16, 1, 1, 16, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (17, 1, 1, 17, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (18, 1, 1, 18, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (19, 1, 1, 19, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (20, 1, 1, 20, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (21, 1, 1, 21, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (22, 1, 1, 22, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (23, 1, 1, 23, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (24, 1, 1, 24, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (25, 1, 1, 25, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (26, 1, 1, 26, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (27, 1, 1, 27, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (28, 1, 1, 28, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (29, 1, 1, 29, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (30, 1, 1, 30, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (31, 1, 1, 31, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (32, 1, 1, 32, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (33, 1, 1, 33, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (34, 1, 1, 34, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (35, 1, 1, 35, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (36, 1, 1, 36, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (37, 1, 1, 37, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (38, 1, 1, 38, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (39, 1, 1, 39, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (40, 1, 1, 40, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (41, 1, 1, 41, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (42, 1, 1, 42, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (43, 1, 1, 43, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (44, 1, 1, 44, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (45, 1, 1, 45, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (46, 1, 1, 46, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (47, 1, 1, 47, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (48, 1, 1, 48, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (49, 1, 1, 49, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (50, 1, 1, 50, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (51, 1, 1, 51, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (52, 1, 1, 52, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (53, 1, 1, 53, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (54, 1, 1, 54, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (55, 1, 1, 55, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (56, 1, 1, 56, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (57, 1, 1, 57, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (58, 2, 2, 1, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (59, 2, 2, 2, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (60, 2, 2, 3, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (61, 2, 2, 4, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (62, 2, 2, 5, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (63, 2, 2, 6, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (64, 2, 2, 7, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (65, 2, 2, 8, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (66, 2, 2, 9, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (67, 2, 2, 10, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (68, 2, 2, 11, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (69, 2, 2, 12, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (70, 2, 2, 13, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (71, 2, 2, 14, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (72, 2, 2, 15, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (73, 2, 2, 16, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (74, 2, 2, 17, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (75, 2, 2, 18, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (76, 2, 2, 19, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (77, 2, 2, 20, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (78, 2, 2, 21, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (79, 2, 2, 22, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (80, 2, 2, 23, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (81, 2, 2, 24, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (82, 2, 2, 25, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (83, 2, 2, 26, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (84, 2, 2, 27, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (85, 2, 2, 28, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (86, 2, 2, 29, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (87, 2, 2, 30, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (88, 2, 2, 31, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (89, 2, 2, 32, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (90, 2, 2, 33, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (91, 2, 2, 34, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (92, 2, 2, 35, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (93, 2, 2, 36, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (94, 2, 2, 37, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (95, 2, 2, 38, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (96, 2, 2, 39, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (97, 2, 2, 40, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (98, 2, 2, 41, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (99, 2, 2, 42, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (100, 2, 2, 43, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (101, 2, 2, 44, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (102, 2, 2, 45, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (103, 2, 2, 46, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (104, 2, 2, 47, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (105, 2, 2, 48, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (106, 2, 2, 49, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (107, 2, 2, 50, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (108, 2, 2, 51, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (109, 2, 2, 52, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (110, 2, 2, 53, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (111, 2, 2, 54, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (112, 2, 2, 55, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (113, 2, 2, 56, 1, GETDATE(), 2, NULL, NULL)
INSERT dbo.PageRoleNRights (Id, UserId, UserTypeId, PageId, IsAllowed, CreatedOn, CreatedBy, UpdatedOn, UpdatedBy) VALUES (114, 2, 2, 57, 1, GETDATE(), 2, NULL, NULL)

SET IDENTITY_INSERT dbo.PageRoleNRights OFF
end